### ISSUE TITLE
Create editor for routesCacheFile.js

### ISSUE THREAD

**Issue by quaso** [quaso/mazda-enhanced-compass-routing#10]

**Comment by brettalcox** [comment]
Trying to run through this code and understand it. I've generated a route from Graphhopper and outputted it to a file. It's one big long file that has all of the coordinates for each turn/text saying (in German) "turn left of 71" etc. Sorry if I'm understanding this navigation feature incorrectly, so the Mazda has to be connected to the internet to make the POST request, then can disconnect? What I'm trying to do is generate the file like above, throw it on my SD and select the route. Where/how do I put this file on the system?

EDIT: Looks like I need to format the output of the file. Do I reformat and put in routesCacheFile.js?

**Comment by quaso** [comment]
German language is default one, because Graphhopper is somewhere from Germany. You have to use locale=en in thr request.

If the route is not cached already (localStorage nor file), then yes, Mazda must be connected to the internet. Once Mazda receives response and you are driving according to the route (+/- 30 metres), then no internet connection is needed any more.

The file with routes is placed directly at the root folder of the sd-card. I do not want to put it into system folder, because when one accidentally remove this folder during the upgrade, the routes will be lost.

What do you mean by " format the output of the file" ?. The routesCacheFile.js contains just one js array variable. Start/destination of the route and data for it. The data are parsed out of Graphhopper response for convenience (see cacheResult method in graph_hopper.js)

**Comment by brettalcox** [comment]
Okay I have the test environment up and running in my web browser, although for some reason even after setting the symlink to my tiles, it still doesnt show map (it shows in the original app without the nav). But I'm still able to click "navigate to" and it properly shows the routing and signs. 

I modified the settings file and made "Home" and set it to my home coords, and when I click "navigate to home" on the menu in the app, it properly shows a route to my house (from work). 

My question is, I have generated a file on my linux machine for the route coordinates using GraphHopper. The file starts off like this

{
  "hints": {
    "visited_nodes.average": "200.0",
    "visited_nodes.sum": "200"
  },
  "paths": [{
    "instructions": [
      {
        "distance": 601.193,
        "sign": 0,
        "interval": [
          0,
          3
        ],
        "text": "Geradeaus auf I 435 E",
        "time": 22781
      },

...... and then the second half of the file continues with the corresponding coords.

```
"descend": 151.99896240234375,
"ascend": 192.2989501953125,
"distance": 22214.441,
"bbox": [
  -94.537992,
  38.854181,
  -94.434988,
  38.953339
],
"weight": 22214.440889,
"time": 1157766,
"points_encoded": false,
"points": {
  "coordinates": [
    [
      -94.53509,
      38.943864
    ],
    [
      -94.533591,
      38.94686
    ],
    [
      -94.532803,
      38.948265
    ],
    [
      -94.532438,
      38.948858
    ],
```

I don't readily have wifi available for my car (lost my hotspot when I unjailbroke my iPhone!), so I want to be able to logon to my computer, generate a route file like above, move it to the SD card, and have the navigation app parse/use this file to show the route without internet.

**Comment by quaso** [comment]
The issue with map... I make some changes for the test environment, becuase the flyandi's wasn't working for me :( I did not want to loose time with find the reason, so I created my own test env. I will concenrate on reverting back to original test env next week.

You can create the data structure in file acceptable format using any web browser. Just use your test env to generate a route (exactly what you described) and then look into browser's localStorage. Copy the values for keys cachedRoute-\* into the file. One value is one item in the CACHED_ROUTES array. I have to create the editor soon :)

**Comment by brettalcox** [comment]
Hmmmmm I'm looking in FireBug and not seeing anything in the localStorage

**Comment by quaso** [comment]
You have to install plugin into firebug
https://addons.mozilla.org/en-US/firefox/addon/firestorage-plus/

This shows all storages in extra tab in firebug

**Comment by brettalcox** [comment]
Still not seeing anything. I input my "work" coordinates for my current location. And then input my "home" coordinates into the "Navigate to" section. Then I click "Navigate to", after a few seconds, the route pops up correctly (still not showing signs for this route (only red X's), yet the example that was loaded by default showed signs). So after the route shows up, I check the localStorage and all values say 'null'.

**Comment by brettalcox** [comment]
Nevermind! lol. Was using the wrong branch. Was using cacheRouting instead of routing-tested-version. All is good now! Thanks

**Comment by brettalcox** [comment]
![](http://i.imgur.com/nmFll1D.jpg)

:D :D :D

**Comment by brettalcox** [comment]
Is the route editor in the export branch completed yet?

**Comment by quaso** [comment]
Not yet, I will finish it next week probably. So far it can show routes stored in routesCacheFile.js. I will add features for adding new routes and maybe editing current.

**Comment by brettalcox** [comment]
Oh okay cool
