### ISSUE TITLE
Export/clear cached routes from localStorage

### ISSUE THREAD

**Issue by quaso** [quaso/mazda-enhanced-compass-routing#12]
Add feature to export&clear routes stored in localStorage. Create web app which will receive these data and will manage them. The app should export the routes to routesCachedFile.js. Either make the app standalone or host it at e.g. Google Engine

**Comment by brettalcox** [comment]
I have a couple nodes and databases, so if you need help with this let me know.

**Comment by quaso** [comment]
Should be implemented, but not tested yet in real Mazda environemnt. Just at localhost and GAE

**Comment by quaso** [comment]
Works perfectly. But, localStorage is cleared by Mazda :( Probably with each start or hard reset. Nevertheless I will switch to WebSQL (issue #19)
