### ISSUE TITLE
Written directions at top of screen

### ISSUE THREAD

**Issue by brettalcox** [quaso/mazda-enhanced-compass-routing#13]
GraphHopper outputs the directions in the JSON as well (i.e. "Turn left on Bannister Road" "Merge onto 71 hwy"). These could be posted at the top of the screen just like "Destination reached".

**Comment by quaso** [comment]
Excellent idea, implemented in no time :)

**Comment by brettalcox** [comment]
Can the notification be hidden after the user selects "clear route"?

**Comment by quaso** [comment]
Ups :) Fixed
