### ISSUE TITLE
Run as a background process

### ISSUE THREAD

**Issue by brettalcox** [quaso/mazda-enhanced-compass-routing#14]
This might be a feature that the Mazda infotainment system is incapable of due to hardware limitations, but the navigation stops when leaving the app. When the Mazda is not connected to the internet, rerouting/restarting the navigation is not possible after returning to the app, therefore routing cannot be continued until you reach a cached location/connect to internet.

**Comment by quaso** [comment]
Destination is stored in localStorage, so once you return to the app, routing to last destination is started automatically.
