### ISSUE TITLE
UI Fixes for driving directions

### ISSUE THREAD

**Issue by brettalcox** [quaso/mazda-enhanced-compass-routing#15]
When the directions are displayed at the top of the screen, during routing, the notifications box appears and disappears continually for the entirety of the route

The text in the notification box will also overflow outside of the box if the driving instruction is too long. 

I did notice, when setting up a route while in park, putting in reverse and backing out of my driveway (the routing disappears because you leave the app for backup camera), then once in drive, clicking the routing again, the flickering and disappearing of the driving instructions is gone.

**Comment by quaso** [comment]
I noticed this today and made a commit "UI minor fixes", which should fix this. I think it is caused by wrong z-indexes in CSS. I will test it tomorrow with the fix.

**Comment by quaso** [comment]
fix is not working :(

**Comment by quaso** [comment]
issue fixed
