### ISSUE TITLE
Offline routing to active routing when user intersects the route

### ISSUE THREAD

**Issue by brettalcox** [quaso/mazda-enhanced-compass-routing#18]
Currently (I think), the offline route only becomes active when the user approaches the start location. What I think would be nice to have, is if you start the route, and then take a wrong turn/different route, but at some point end up on the route again, the navigation will start and continue from that point. 

This would also be really nice for when I've already left the start location and proceeded on my way for a little while before selecting the destination.

**Comment by quaso** [comment]
Already implemented in 'offline' branch. Currently testing :-) It even displays you all cached routes to chosen destination, if you are offline.

**Comment by brettalcox** [comment]
Hmmm. When I was driving last night, when i select a route offline (and im not anywhere close to it) it will show the route on the map, but then once i hop on the route and start driving on it, the directions/signs never show on the screen.

**Comment by quaso** [comment]
Which commit were you testing? I think I fixed this already.

**Comment by brettalcox** [comment]
Oh okay, maybe I didn't get that last commit. I'll grab that and then test again later
