### ISSUE TITLE
please make this app more interesting and continue to developp it more please

### ISSUE THREAD

**Issue by mahouda28** [quaso/mazda-enhanced-compass-routing#23]
hi,
i please continue develop this app please to make her a menu to make work destination or to see meteo to the place where are the car on the route to make her more very intuitive and very sophisticated because it lacks a lot of navigation ( directions not working, direction with voice, to spell about the city to make a destination to the place where the car is now , make meteo work to the place where is the destination or the meteo along the direction instantly ) and how to make import POI i don't find POI for tunisia and i connect the car to the internet and after i work this app gps but i dont have no menu or to tape the destination please help me and male this app to continue progress dont stop please this worderfull. please abswer me as soon as possible.
NB:The routing not working to me and i have no one supporting me to resolve this problem i have just the yellow for the car where is just this but i dont have to make direction enabled.

please please help me

thanks at all.

**Comment by quaso** [comment]
Wow, you want to make semi-professional navigation out of this. I would also like to, but this is spare time project which is not making any money :) :(
