### ISSUE TITLE
i dont have routing with connexion online

### ISSUE THREAD

**Issue by mahouda28** [quaso/mazda-enhanced-compass-routing#24]
please i dont have routing and how to tape the place (destination) to place on it and how i create POI to tunisia .

please support me and make me a help because they dont work to me this app need to be more interesting that missed many fonctionnality that miss menu to configure or to tape with virtuall keyboard like this original app for mazda navigation compass.

thanks .

**Comment by quaso** [comment]
There is an existing app to edit the routes or destinations. See https://github.com/quaso/mazda-enhanced-compass-routing/wiki/Routes-editor

I wanted to add an interactive keyboard, but found out that it will take too much time. I contributed into this project for fun and was developing it in my spare time. Fun part was exceeded and so I was not finding any spare time for this anymore. I also sold Mazda and won't by it in next 100 years, unless they fix some crucial issues.

**Comment by mahouda28** [comment]
hi,mazda is the best at all technologie , motor and design.please i understand when i would a routes i connect to my pc to download a file toimport it in my sd card to see the destination.if it s this there s more tiring to make this if you would love to place in any town that you dont know it and sometime i dont have time to open my pc because i have many work in the car is more interesting then that why you dont make it online is more interesting directly to mzdconnect to website .
please


      De : quaso <notifications@github.com>
 À : quaso/mazda-enhanced-compass-routing <mazda-enhanced-compass-routing@noreply.github.com> 
Cc : mahouda28 <mahdijoujou@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Vendredi 8 septembre 2017 9h39
 Objet : Re: [quaso/mazda-enhanced-compass-routing] i dont have routing with connexion online (#24)
   
There is an existing app to edit the routes or destinations. See https://github.com/quaso/mazda-enhanced-compass-routing/wiki/Routes-editorI wanted to add an interactive keyboard, but found out that it will take too much time. I contributed into this project for fun and was developing it in my spare time. Fun part was exceeded and so I was not finding any spare time for this anymore. I also sold Mazda and won't by it in next 100 years, unless they fix some crucial issues.—

**Comment by quaso** [comment]
Then just buy the original navigation. Sorry. The software used in Infotainment is Opera release in 2012, not fully supporting HTML5. That is also one of the reason, why I sold Mazda - outdated technologies. Nowadays cars are not about engine, design, but also about software.

**Comment by mahouda28** [comment]
hi,i would love just i make you simple idea why do you can make just simple script to install it in mzdconnect to make this manipulation directly to mzdconnect connect to the internet and no use computer to upload the routes and copy it to sd card just mzdconnect connect to the internet give the routes in the site of mazda routes edit directly and the user cannot see anything just he see the routes simply who love it with direction with voice .
do you can make this poosible?

thanks nice to meet you.


      De : quaso <notifications@github.com>
 À : quaso/mazda-enhanced-compass-routing <mazda-enhanced-compass-routing@noreply.github.com> 
Cc : mahouda28 <mahdijoujou@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Vendredi 8 septembre 2017 9h39
 Objet : Re: [quaso/mazda-enhanced-compass-routing] i dont have routing with connexion online (#24)
   
There is an existing app to edit the routes or destinations. See https://github.com/quaso/mazda-enhanced-compass-routing/wiki/Routes-editorI wanted to add an interactive keyboard, but found out that it will take too much time. I contributed into this project for fun and was developing it in my spare time. Fun part was exceeded and so I was not finding any spare time for this anymore. I also sold Mazda and won't by it in next 100 years, unless they fix some crucial issues.—
